name: Build/Push (tag)

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - run: go get -t -v ./...
      - run: go test -v -race ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}

  upload:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        include:
          - os: linux
            arch: 386
          - os: linux
            arch: amd64
          - os: linux
            arch: arm
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: freebsd
            arch: 386
          - os: freebsd
            arch: amd64
          - os: windows
            arch: 386
            extension: '.exe'
          - os: windows
            arch: amd64
            extension: '.exe'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Download go dependencies
        run: go get -t -v ./...

      - name: Install the needed vendors
        run: GO111MODULE=on go mod vendor

      - name: Create release (${{ matrix.os }}-${{ matrix.arch }})
        run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -a -ldflags '-s -w' -o wireguard_exporter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }} ./
      
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}${{ matrix.extension }}
          asset_path: ./wireguard_exporter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}
          asset_name: wireguard_exporter-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}
          asset_content_type: application/octet-stream
